-- MySQL Script generated by MySQL Workbench
-- 02/25/16 11:38:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diwoo10_symfony_monBlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diwoo10_symfony_monBlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diwoo10_symfony_monBlog` DEFAULT CHARACTER SET utf8 ;
USE `diwoo10_symfony_monBlog` ;

-- -----------------------------------------------------
-- Table `diwoo10_symfony_monBlog`.`auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diwoo10_symfony_monBlog`.`auteurs` (
  `id_auteur` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(256) NOT NULL,
  `mdp` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_auteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diwoo10_symfony_monBlog`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diwoo10_symfony_monBlog`.`articles` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(256) NOT NULL,
  `message` TEXT NOT NULL,
  `id_auteur` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `id_auteurs_idx` (`id_auteur` ASC),
  CONSTRAINT `id_auteurs`
    FOREIGN KEY (`id_auteur`)
    REFERENCES `diwoo10_symfony_monBlog`.`auteurs` (`id_auteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
