<?php
/*
* Implements hook_preprocess_HOOK
*/
function menuDeroulant_preprocess_page(&$variables) {
    $clean_menu = array();
    $menu = menu_tree_all_data("main-menu");

    // Création du tableau que l'on enverra au moteur de template
    foreach($menu as $item) {
        $clean_menu[]=array(
            "link"=>$item["link"]["link_path"],
            "title"=>$item["link"]["title"],
            "childs"=>parse_menu_child($item["below"]));
    }

    // Injection du menu dans les variables utilisées par le moteur de template
    $variables["menuDeroulant_menu"]=$clean_menu;
}

// Traitement des sous menus
function parse_menu_child($items) {
    $child_menu=array();
    foreach($items as $key=>$item)
        $child_menu[]=array(
            "link"=>$item["link"]["link_path"],
            "title"=>$item["link"]["title"],
            "childs"=>parse_menu_child($item["below"]));

    return($child_menu);
}

/*
* Implements hook_theme
*/
function menuDeroulant_theme($existing,$type,$theme,$path) {
    return(array("menuDeroulant_menu"=>array("variables"=>array())));
}

// Génération du code HTML du menu
function theme_menuDeroulant_menu($menu) {
    static $first;
    $output="";
    if(count($menu)>=1) {
        $first++;
        if($first==1){
            $output.="<ul id='main-menu-links'>";
        } else {
            $output.="<ul>";
        }

        foreach($menu as $item) {
            if(is_array($item)){
                if($first==1)
                    $output.="<li class='inline clearfix'>".l(t($item["title"]),$item["link"]);
                else $output.="<li class='inline clearfix'>".l(t($item["title"]),$item["link"]);

                if(isset($item["childs"]))  {
                    if(count($item["childs"]>=1)) {
                            $output.=theme_menuDeroulant_menu($item["childs"]);
                    }
                }
                $output.="</li>";
            }
        }
        $output.="</ul>";
    }
    return($output);
}